# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mDVhPRQOVD_y7ZwVrbhko_T1zq18PgTx
"""

import numpy as np
import pandas as pd
from google.colab import drive
from datetime import datetime
drive.mount('/content/drive')

df = pd.read_csv('/content/drive/MyDrive/dataset/200k_train.csv')

# for i, item in enumerate(df['created']):
#       time = datetime.strptime(item, "%Y-%m-%d %H:%M:%S")
#       df.loc[i, 'created'] = int(time.minute)

df.head()

# df = df.drop_duplicates(subset=['Segment', 'oblast', 'city', 'os', 'osv'])

df.info()

# df = df.drop_duplicates(subset=['Segment', 'oblast', 'city', 'os', 'osv'])
# new_index = range(len(df))
# df = df.reindex(new_index)
# df = df.dropna()
# df.head(50)

def get_stat(df):
  ans = [0, 0, 0, 0, 0,]
  listSegment = np.unique(df['Segment'])
  move = [[], [], [], [], []]
  subgamecategory = [[], [], [], [], []]
  os = [[], [], [], [], []]
  obl = [[], [], [], [], [], []]
  version = [[], [], [], [], []]
  for i, item in enumerate(df['Segment']):
    ans[item-1]+=1
    move[item-1].append(df['gamecategory'][i])
    obl[item-1].append(df['oblast'][i])
    os[item-1].append(df['os'][i])
    subgamecategory[item-1].append(df['subgamecategory'][i])
    version[item-1].append(df['osv'][i])
  game = []
  osi=[]
  ios = []
  veri = []
  obli = []
  for i in range(5):
    ans[i] = ans[i]/len(df['Segment'])*100
    dat = pd.DataFrame(move[i]).value_counts()
    col = dat.index.tolist()
    game.append(dat[0]/len(move[i]))
    dat = pd.DataFrame(os[i]).value_counts()
    osi.append(dat[0]/len(os[i]))
    ios.append((len(os[i])-dat[0])/len(os[i]))
    dat = pd.DataFrame(obl[i]).value_counts()
    ufa = str(dat.index.tolist()[0])
    ufa = ufa[2:len(ufa)-3]
    obli.append(ufa)
    dat = pd.DataFrame(version[i]).value_counts()
    code = str(dat.index.tolist()[0])
    code = code[2:len(code)-3]
    veri.append(code)
  pas={
      'Segment':listSegment,
      'Сoverage': ans,
      'oblast' : obli,
      'osv': veri,
      'Love Game': game,
      'Android':osi,
      'IOS': ios
  }

  df_ret = pd.DataFrame(pas)
  return df_ret

stat = get_stat(df)

stat.head()

stat.to_csv()

import matplotlib.pyplot as plt

df[''].value_counts().plot(kind='bar')

plt.show()

# ans = {
  #     'Games': game,
  #     'Applications': apl,
  #     'Lifestyle': lfs,
  #     'Education': edc,
  #     'Entertainment': ent,
  #     'Music': mus,
  #     'Utilities': utt,
  #     'Shopping': shp,
  #     'Book': bok,
  #     'Social Networking': soc,
  #     'Photo & Video': pht,
  #     'Finance': fin,
  #     'IAB9-30': iab,
  #     'Graphics & Design': grp,
  #     'Sports': spt,
  #     'Medical': med,

  # }
  '''
    for i in range(5):
     
     game.append(a[0])
     apl.append(a[1])
     lfs.append(a[2])
     edc.append(a[3])
     ent.append(a[4])
     mus.append(a[5])
     utt.append(a[6])
     shp.append(a[7])
     bok.append(a[8])
     soc.append(a[9])
     pht.append(a[10])
     fin.append(a[11])
     iab.append(a[12])
     grp.append(a[13])
     spt.append(a[14])
     med.append(a[15])

  ans = {
      'Games': game,
      'Applications': apl,
      'Lifestyle': lfs,
      'Education': edc,
      'Entertainment': ent,
      'Music': mus,
      'Utilities': utt,
      'Shopping': shp,
      'Book': bok,
      'Social Networking': soc,
      'Photo & Video': pht,
      'Finance': fin,
      'IAB9-30': iab,
      'Graphics & Design': grp,
      'Sports': spt,
      'Medical': med,

  }
  clear_df = clear_duplicate(df)
  df['created']= pd.to_datetime(df['created'])
  def clear_duplicate(data):
  for i in range(len(data)):
    for j in range(len(data)):
      if i!=j and data['Segment'][i] == data['Segment'][j] and data['city'][i]==data['city'][j] and data['osv'][i]==data['osv'][j] and abs(df['created'][i]-df['created'][j])<100:
        data.drop()
  return data
  '''